version: '2'
services:
  vault:
    image: "vault"
    command: vault server -dev
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_DEV_ROOT_TOKEN_ID: some-token
      VAULT_LOCAL_CONFIG: >
        {
          "disable_mlock": true
        }
    ports:
    - "8200:8200"
